FakeShop/Models/Cart.cs
namespace FakeShop.Models
{
    public class Cart
    {
        public int Id { get; set; }
        public List<CartItem> Items { get; set; }

        public string UserId { get; set; }
        public User User { get; set; }
    }
}

FakeShop/Models/CartItem.cs
using System.ComponentModel.DataAnnotations;

namespace FakeShop.Models
{
    public class CartItem
    {
        public int Id { get; set; }
        [Required]
        public int VendorCode { get; set; }
        [Required]
        public int Amount { get; set; }

        public int CartId { get; set; }
        public Cart Cart { get; set; }
    }
}

FakeShop/Models/ErrorViewModel.cs
namespace FakeShop.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FakeShop/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace FakeShop.Models
{
    public class Product
    {
        public int Id { get; set; }
        [Required]
        public int VendorCode { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public bool IsSelling { get; set; }
        [Required]
        public bool IsHidden { get; set; }
        [Required]
        public double CurrentPrice { get; set; }
        public double PreviousPrice { get; set; }
        [Required]
        public int Quantity { get; set; }
        public List<ProductImage> Images { get; set; }
    }
}

FakeShop/Models/ProductImage.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace FakeShop.Models
{
    public class ProductImage
    {
        public int Id { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }
        public string ImagePath { get; set; }

        public int ProductId { get; set; }
        public Product Product { get; set; }
    }
}

FakeShop/Models/User.cs
using Microsoft.AspNetCore.Identity;

namespace FakeShop.Models
{
    public class User : IdentityUser
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public SexOptions Sex { get; set; }
        public DateTime BirthDate { get; set; }
        public Cart Cart { get; set; }
    }

    public enum SexOptions
    {
        Male,
        Female
    }
}

FakeShop/Controllers/CMS/CmsController.cs
using FakeShop.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace FakeShop.Controllers
{
    public partial class CmsController : Controller
    {
        private readonly ILogger _logger;

        public CmsController(ILogger<CmsController> logger)
        {
            _logger = logger;
        }

        [Route("cms")]
        public IActionResult Home()
        {
            return View();
        }
    }
}

FakeShop/Controllers/CMS/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using FakeShop.Models;
using FakeShop.Repositories;

namespace FakeShop.Controllers.CMS
{
    [Route("cms/products/")]
    public partial class ProductController : Controller
    {
        private readonly ILogger _logger;
        private readonly ProductRepository _productRepository;

        public ProductController(ILogger<ProductController> logger, ProductRepository productRepository)
        {
            _logger = logger;
            _productRepository = productRepository;
        }

        [Route("")]
        public async Task<IActionResult> List()
        {
            return View("../Cms/ProductsList", await _productRepository.GetAll());
        }

        [Route("create")]
        [HttpGet]
        public IActionResult Create()
        {
            return View("../Cms/ProductCreate");
        }

        [Route("create")]
        [HttpPost]
        public async Task<IActionResult> Create(Product p)
        {
            if (!ModelState.IsValid)
            {
                return View("../Cms/ProductCreate", p);
            }

            await _productRepository.Create(p);
            return Content($"Product \"{p.Name}\" created");
        }

        [Route("edit")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            throw new NotImplementedException();
        }

        [Route("edit/{id:int}")]
        [HttpPost]
        public IActionResult Edit(Product p)
        {
            throw new NotImplementedException();
        }

        [Route("delete/{id:int}")]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            throw new NotImplementedException();
        }
    }
}

FakeShop/Controllers/CMS/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using FakeShop.Models;

namespace FakeShop.Controllers.CMS
{
    [Route("[controller]/products/")]
    public partial class CmsController : Controller
    {

        [Route("")]
        public IActionResult List()
        {
            throw new NotImplementedException();
        }

        [Route("create")]
        [HttpGet]
        public IActionResult Create()
        {
            throw new NotImplementedException();
        }

        [Route("create")]
        [HttpPost]
        public IActionResult Create(Product p)
        {
            throw new NotImplementedException();
        }

        [Route("edit")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            throw new NotImplementedException();
        }

        [Route("edit/{id:int}")]
        [HttpPost]
        public IActionResult Edit(Product p)
        {
            throw new NotImplementedException();
        }

        [Route("delete/{id:int}")]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            throw new NotImplementedException();
        }
    }
}

FakeShop/Controllers/HomeController.cs
using FakeShop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FakeShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Route("/")]
        public IActionResult Home() => View();

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FakeShop/Views/Cms/ProductCreate.cshtml
@model FakeShop.Models.Product

@{
    ViewData["Title"] = "ProductCreate";
}

<h1>ProductCreate</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Product">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="VendorCode" class="control-label"></label>
                <input asp-for="VendorCode" class="form-control" />
                <span asp-validation-for="VendorCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsSelling" /> @Html.DisplayNameFor(model => model.IsSelling)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsHidden" /> @Html.DisplayNameFor(model => model.IsHidden)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CurrentPrice" class="control-label"></label>
                <input asp-for="CurrentPrice" class="form-control" />
                <span asp-validation-for="CurrentPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PreviousPrice" class="control-label"></label>
                <input asp-for="PreviousPrice" class="form-control" />
                <span asp-validation-for="PreviousPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List" asp-controller="Product">Back to List</a>
</div>

FakeShop/Views/Cms/ProductsList.cshtml
@model IEnumerable<FakeShop.Models.Product>

@{
    ViewData["Title"] = "Products List";
}

<h1>Products List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.VendorCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsSelling)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsHidden)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrentPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PreviousPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.VendorCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsSelling)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsHidden)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurrentPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PreviousPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

FakeShop/Views/Home/Home.cshtml
<a asp-action="Home" asp-controller="Cms">CMS</a>
<a asp-action="List" asp-controller="Product">Products list</a>

FakeShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FakeShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FakeShop.styles.css" asp-append-version="true" />
</head>
<body>
    <p>Когда-то здесь будет стартовый главный шаблон. Но пока здесь <b><i>нихуя</i></b></p>
    
    @RenderBody()

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>